kind: lambdastack-cluster
title: "LambdaStack Cluster Config"
provider: aws
name: "default"
build_path: "build/path"  # This gets dynamically built

#### Begin - Add your info HERE

admin_user_name: ubuntu                     # <ubuntu> for AWS Ubuntu or <operations> for all other OS
admin_user_key_path: lambdastack-operations # You can leave it and make your SSH keys this name or change the name to your SSH key name
cloud_use_public_ips: True                  # SECURITY - Change this to False if you have a VPN or direct connect
cloud_credentials_key: XXXXXXXXXXXXX        # Your AWS Subscription Key
cloud_credentials_secret: XXXXXXXXXXXXX     # Your AWS Subscription Secret

#### End - Add your info HERE

specification:
  name: lambdastack
  prefix: staging  # Can be anything you want that helps quickly identify the cluster
  admin_user:
    name: *admin_user_name # YOUR-ADMIN-USERNAME
    key_path: *admin_user_key_path # YOUR-SSH-KEY-FILE-NAME
    path: "/shared/build/<name of cluster>/keys/ssh/lambdastack-operations" # Will get dynamically created
  cloud:
    k8s_as_cloud_service: False
    use_public_ips: *cloud_use_public_ips # When not using public IPs you have to provide connectivity via private IPs (VPN)
    credentials:
      key: *cloud_credentials_key # AWS Subscription Key
      secret: *cloud_credentials_secret # AWS Subscription Secret
    default_os_image: default
  components:
    repository:
      count: 1
    kubernetes_master:
      count: 1
    kubernetes_node:
      count: 2
    logging:
      count: 1
    monitoring:
      count: 1
    kafka:
      count: 2
    postgresql:
      count: 1
    load_balancer:
      count: 1
    rabbitmq:
      count: 1
