---
- name: ODFE | Load /etc/elasticsearch/elasticsearch.yml
  slurp:
    src: /etc/elasticsearch/elasticsearch.yml
  register: _elasticsearch_yml

- name: OFDE | Patch /etc/elasticsearch/elasticsearch.yml (switch to generated certificates)
  copy:
    dest: /etc/elasticsearch/elasticsearch.yml
    content: "{{ _patched_content | to_nice_yaml }}"
    mode: u=rw,g=rw,o=
    owner: root
    group: elasticsearch
    backup: true
  vars:
    _lambdastack_subjects:
      admin: "{{ certificates.files.admin.cert.subject }}"
      node:  "{{ certificates.files.node.cert.subject }}"
    _lambdastack_dn_attributes:
      admin: "{{ certificates.dn_attributes_order | intersect(_lambdastack_subjects.admin.keys()) }}"
      node:  "{{ certificates.dn_attributes_order | intersect(_lambdastack_subjects.node.keys()) }}"
    _lambdastack_DNs:
      admin: >-
        {{ _lambdastack_dn_attributes.admin | zip(_lambdastack_dn_attributes.admin | map('extract', _lambdastack_subjects.admin))
                                         | map('join','=') | join(',') }}
      node: >-
        {{ _lambdastack_dn_attributes.node | zip(_lambdastack_dn_attributes.node | map('extract', _lambdastack_subjects.node))
                                        | map('join','=') | join(',') }}
    _old_content: >-
      {{ _elasticsearch_yml.content | b64decode | from_yaml }}
    _updated_settings:
      opendistro_security.authcz.admin_dn: >-
        {{ _old_content['opendistro_security.authcz.admin_dn'] | default([]) | map('replace', ', ', ',')
                                                               | union([_lambdastack_DNs.admin]) }}
      opendistro_security.nodes_dn: >-
        {{ _old_content['opendistro_security.nodes_dn'] | default([])
                                                        | union([_lambdastack_DNs.node]) }}

      opendistro_security.ssl.http.pemcert_filepath: "{{ certificates.files.node.cert.filename }}"
      opendistro_security.ssl.http.pemkey_filepath:  "{{ certificates.files.node.key.filename }}"
      opendistro_security.ssl.transport.pemcert_filepath: "{{ certificates.files.node.cert.filename }}"
      opendistro_security.ssl.transport.pemkey_filepath:  "{{ certificates.files.node.key.filename }}"

      opendistro_security.ssl.http.pemtrustedcas_filepath:      "{{ certificates.files.root_ca.cert.filename }}"
      opendistro_security.ssl.transport.pemtrustedcas_filepath: "{{ certificates.files.root_ca.cert.filename }}"

    _patched_content: >-
      {{ _old_content | combine(_updated_settings) }}

- include_tasks:
    file: utils/restart-node.yml
  vars:
    target_inventory_hostname: "{{ inventory_hostname }}"
    skip_waiting_for_node: true  # because after restart demo certificate stops working

# Test API access using LambdaStack admin cert
- include_tasks:
    file: utils/assert-api-access.yml
  vars:
    es_api:
      cert_type: LambdaStack
      cert_path: &ls_cert_path "{{ (certificates.dirs.certs, certificates.files.admin.cert.filename) | path_join }}"
      key_path:  &ls_key_path  "{{ (certificates.dirs.certs, certificates.files.admin.key.filename)  | path_join }}"
      url: "{{ hostvars[inventory_hostname].es_api.url }}"
    fail_msg: API access test failed.

- name: Update API related facts to use LambdaStack admin certificate instead of demo
  set_fact:
    es_api: "{{ es_api | combine(_es_api) }}"
  vars:
    _es_api:
      cert_type: LambdaStack
      cert_path: *ls_cert_path
      key_path:  *ls_key_path

# Reload config file to preserve patched settings (sets 'existing_config' fact)
- include_tasks: utils/get-config-from-files.yml
