---
# Ansible playbook for disabling/enabling repositories before/after LambdaStack installation

- hosts: all
  become: true
  become_method: sudo
  tasks:
    - import_role:
        name: repository
        tasks_from: teardown
