---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ls-dummy.fullname" . }}
  labels:
    {{- include "ls-dummy.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    defaults
        timeout connect 10s
        timeout client 30s
        timeout server 30s
    frontend fe
        bind 0.0.0.0:80
        use_backend be
    backend be
        mode http
        errorfile 503 /config/ls-dummy.http
  ls-dummy.http: |
    HTTP/1.0 200 Found
    Cache-Control: no-cache
    Connection: close
    Content-Type: application/json

    {"message": "ls-dummy"}
