---
pg:
  base_dir:
    Debian: /var/lib/postgresql
    RedHat: /var/lib/pgsql
  bin_dir:
    Debian: /usr/lib/postgresql/14/bin
    RedHat: /usr/pgsql-14/bin
  config_dir:
    Debian: /etc/postgresql/14/main
    RedHat: /var/lib/pgsql/14/data
  data_dir:
    Debian: /var/lib/postgresql/14/main
    RedHat: /var/lib/pgsql/14/data
  instantiated_service_name:
    Debian: postgresql@14-main
    RedHat: null
  packages:
    common:
      Debian:
        - postgresql-client-common
        - postgresql-common
      RedHat: []
    version_specific:
      Debian:
        - postgresql-14
        - postgresql-client-14
      RedHat:
        - postgresql14-server
  service_name:
    Debian: postgresql
    RedHat: postgresql-14
  version: 14

pgaudit:
  package_name:
    Debian: postgresql-14-pgaudit
    RedHat: pgaudit15_14
  version:
    Debian: "1.5.0"
    RedHat: "1.5.0"

repmgr:
  bin_dir:
    Debian: /usr/bin
    RedHat: /usr/pgsql-14/bin
  config_dir:
    Debian: /etc/postgresql/14/main
    RedHat: /etc/repmgr/14
  package_name:
    Debian: postgresql-14-repmgr
    RedHat: repmgr14
  service_name:
    Debian: repmgrd
    RedHat: repmgr14
  version:
    Debian: "5.2.1"
    RedHat: "5.2.1"

pgbouncer:
  group:
    Debian: postgres
    RedHat: pgbouncer
  logfile:
    Debian: /var/log/postgresql/pgbouncer.log
    RedHat: /var/log/pgbouncer/pgbouncer.log
  pidfile:
    Debian: /var/run/postgresql/pgbouncer.pid
    RedHat: /var/run/pgbouncer/pgbouncer.pid
  user:
    Debian: postgres
    RedHat: pgbouncer
  version:
    Debian: "1.16.0"
    RedHat: "1.16.0"
